<!--Assignment 3: CSIT128 - Question 4
    Kazi Swad Abdullah, SN: 5220683
    Question 4 -->

<?xml version="1.0" standalone="yes"?>

<!DOCTYPE audit [
<!ELEMENT audit (subject*)>
<!ATTLIST audit campus CDATA #REQUIRED>
<!ATTLIST audit year CDATA #REQUIRED>
<!ATTLIST audit session CDATA #REQUIRED>
<!ELEMENT subject (code,title,statistics)>
<!ATTLIST subject sid CDATA #REQUIRED>
<!ELEMENT code (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT statistics (enrol,withdrawn)> 
<!ELEMENT enrol (#PCDATA)>
<!ELEMENT withdrawn (#PCDATA)>
]>

<audit campus="Woolloomooloo" year="2000" session="A">
 <subject sid="0769642">
 <code>MATH101</code>
 <title>Calculus</title>
 <statistics>
 <enrol>170</enrol>
 <withdrawn>31</withdrawn>
 </statistics>
 </subject>
 <subject sid="1734231">
 <code>MATH234</code>
 <title>Abstract Algebra</title>
 <statistics>
 <enrol>40</enrol>
 <withdrawn>15</withdrawn>
 </statistics>
 </subject>
</audit>
